language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
deploy:
  provider: heroku
  app: twclient
  api_key: "d70af397-0ed2-424d-9a97-0f7503efeff0"
